### ISSUE TITLE
Request for Compatibility

### ISSUE THREAD

**Issue by CanecaKun** [0vergrown/Origins-Dietary-Delights#1]
Hello! Ive read your mod page and i want to know if there is a plan to add compatibility for the following mods:
- Quality Crops
- Quality's Delight
- Ocean's Delight
- Silent's Delight
- Let's do series (candlelight, vinery, bakery) (not sure if first one has foods)

**Comment by CanecaKun** [comment]
If there is an easy way to config stuff into your datapack/mod please let me know, if its possible i can add the items to the proper tags myself since i need it for my modpack

**Comment by 0vergrown** [comment]
> Hello! Ive read your mod page and i want to know if there is a plan to add compatibility for the following mods:
> 
> * Quality Crops
> * Quality's Delight
> * Ocean's Delight
> * Silent's Delight
> * Let's do series (candlelight, vinery, bakery) (not sure if first one has foods)

Thank you for the suggestion, as of right now. I've started on this and have already added Quality Crops, Quality's Delight, Ocean's Delight, and Silent's Delight. Those are fully implemented. As of writing this, I am currently working on Let's Do, specifically bakery. I can't guarantee when it will be done or full compatibility for Let's Do, simply because it's a lot and I do have work so if I don't finish by the next commit, it will probably be the next but as of right now that is what's left from your suggestion

**Comment by CanecaKun** [comment]
Damn you're fast, good job!
Thank you for your effort and attention!
Does the last version dated 22th of this month on modrinth have those implementations?

**Comment by myriadh** [comment]
Hi! I would like to join in and request compatibility with the following mods: 

- Bountiful Fares
- Brewin' and Chewin'
- Spawn
- Nether Additions
- Nears
- End's Phantasm
- Galosphere
- Immersive Weathering

There is no rush of course and I appreciate all of the good work!!
