### ISSUE TITLE
Keep old versions on Modrinth

### ISSUE THREAD

**Issue by linaraincalzando** [0vergrown/Origins-Dietary-Delights#3]
It would be nice to see the different versions for proper version tracking on the user side. It is also out of the ordinary just to see the latest version.

**Comment by 0vergrown** [comment]
Maybe? To me, it seems pointless in this case because older versions are less compatible versions with fewer mods covered. Maybe a more detailed changelog if you want to see the process, but I personally don't get it when all the supported mods are listed, and with each update, the pack becomes more compatible with more mods

**Comment by linaraincalzando** [comment]
I can understand that, being able to track changes in mods and having easy access to previous versions tends to be really important for tracking in modpacks. Not only for documentation but also because you will have mods that only work on certain versions and being able to track down what has changed between the versions especially if you miss multiple updates. On top of that if your mod is added to modpacks if you dont have the version that is in the pack it will just not be able to be pulled making the point of adding your mod to the pack useless.
